//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMOGA_JonathanZarama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostUser
    {
        public System.Guid ID { get; set; }
        public System.Guid User { get; set; }
        public System.Guid Post { get; set; }
    
        public virtual Post Post1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
